language: go
go:
  - 1.2
  - 1.5
  - 1.6
  - 1.7

before_install:
  - echo -e "machine github.com\n  login zxjsdp\n  password $CI_USER_TOKEN" >> ~/.netrc
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

install:
  - git clone https://zxjsdp:$CI_USER_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - go get github.com/zxjsdp/nodefinder-go/cmd/nodefinder-go

script:
  - go test -v ./...

