language: go
go:
 - 1.2
 - 1.5
 - 1.6
 - 1.7

before_install:
  - echo -e "machine github.com\n  login zxjsdp\n  password $CI_USER_TOKEN" >> ~/.netrc

install:
  - git clone https://zxjsdp:$CI_USER_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT

script:
 - go test -v ./...

