language: go
go:
 - 1.2
 - 1.5
 - 1.6
 - 1.7

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

#install:
#  - go get github.com/zxjsdp/nodefinder-go/cmd/nodefinder-go

script:
 - go test -v ./...

